### ISSUE TITLE
'SO_REUSEPORT' not supported

### ISSUE THREAD

**Issue by brucemelo** [ebarlas/microhttp#11]
Exception in thread "main" java.lang.UnsupportedOperationException: 'SO_REUSEPORT' not supported
	at java.base/sun.nio.ch.ServerSocketChannelImpl.setOption(ServerSocketChannelImpl.java:212)
	at org.microhttp.EventLoop.<init>(EventLoop.java:80)

**Comment by ebarlas** [comment]
Thank you for catching this! I miss the if-guards for those socket options. I'll add the other in as well.
